export const MOCK_STOCKS = [
  {
    id: '1',
    symbol: 'AAPL',
    name: 'Apple Inc.',
    price: 235.42,
    change: 2.5, 
  },
  {
    id: '2',
    symbol: 'GOOGL',
    name: 'Alphabet Inc.',
    price: 168.75,
    change: -1.2,
  },
  {
    id: '3',
    symbol: 'MSFT',
    name: 'Microsoft Corporation',
    price: 445.89,
    change: 3.8,
  },
  {
    id: '4',
    symbol: 'TSLA',
    name: 'Tesla Inc.',
    price: 312.50,
    change: -5.3,
  },
  {
    id: '5',
    symbol: 'AMZN',
    name: 'Amazon.com Inc.',
    price: 198.20,
    change: 1.9,
  },
  {
    id: '6',
    symbol: 'META',
    name: 'Meta Platforms Inc.',
    price: 567.45,
    change: 4.2,
  },
  {
    id: '7',
    symbol: 'NVDA',
    name: 'NVIDIA Corporation',
    price: 987.65,
    change: 6.1,
  },
  {
    id: '8',
    symbol: 'BTC',
    name: 'Bitcoin',
    price: 52340.00,
    change: 8.5,
  },
];

export const TASK3_STOCKS = [
  {
    id: '1',
    symbol: 'AAPL',
    name: 'Apple Inc.',
    price: 235.42,
    change: 2.5,
  },
  {
    id: '2',
    symbol: 'GOOGL',
    name: 'Alphabet Inc.',
    price: 168.75,
    change: -1.2,
  },
  {
    id: '3',
    symbol: 'MSFT',
    name: 'Microsoft Corporation',
    price: 445.89,
    change: 3.8,
  },
  {
    id: '4',
    symbol: 'TSLA',
    name: 'Tesla Inc.',
    price: 312.50,
    change: -5.3,
  },
  {
    id: '5',
    symbol: 'AMZN',
    name: 'Amazon.com Inc.',
    price: 198.20,
    change: 1.9,
  },
  {
    id: '6',
    symbol: 'META',
    name: 'Meta Platforms Inc.',
    price: 567.45,
    change: 4.2,
  },
  {
    id: '7',
    symbol: 'NVDA',
    name: 'NVIDIA Corporation',
    price: 987.65,
    change: 6.1,
  },
  {
    id: '8',
    symbol: 'BTC',
    name: 'Bitcoin',
    price: 52340.00,
    change: 8.5,
  },
  {
    id: '9',
    symbol: 'ETH',
    name: 'Ethereum',
    price: 3125.50,
    change: 5.2,
  },
  {
    id: '10',
    symbol: 'NFLX',
    name: 'Netflix Inc.',
    price: 287.30,
    change: -2.1,
  },
  {
    id: '11',
    symbol: 'INTC',
    name: 'Intel Corporation',
    price: 34.25,
    change: -8.5,
  },
  {
    id: '12',
    symbol: 'AMD',
    name: 'Advanced Micro Devices',
    price: 195.75,
    change: 12.3,
  },
];